### ISSUE TITLE
Critical dependency since crypto-browserify@3.2.6

### ISSUE THREAD

**Issue by jhnns** [webpack/node-libs-browser#15]
@dominictarr introduced with https://github.com/dominictarr/crypto-browserify/commit/9284566e7e8e468c0d30bf946ed8342494836c8d a change which triggers a critical dependency warning due to a dynamic require.

What should we do @sokra? ^^

**Comment by timcash** [comment]
I am having this problem with "crypto-browserify": "^3.9.13", and webpack 1.7.3
