### ISSUE TITLE
License of dependent package is unknown

### ISSUE THREAD

**Issue by kamoqq** [webpack/node-libs-browser#17]
Please update the crypto-browserify version of the dependent packages to the latest.
License of ripemd160@0.2.0 of dependent packages of crypto-browserify@3.3.0 is unknown.
It will be solved by the crypto-browserify to the latest version.

**Comment by PedroNorte** [comment]
+1

**Comment by terinjokes** [comment]
This has been resolved (for Webpack 2) at some point. `crypto-browserify` now includes `ripemd160@1.0.01` which defines the license as the 3-Clause BSD.

**Comment by jhnns** [comment]
We will bump node-libs-browser to `^1.1.0` in webpack-1, see https://github.com/webpack/webpack/issues/3355

**Comment by jhnns** [comment]
There was a hidden breaking change with `crypto-browserify` so that we couldn't upgrade it to the most recent version. However, [this PR](https://github.com/webpack/webpack/pull/3368) introduces the most recent versions without breaking change to webpack-1.
