### ISSUE TITLE
Version bumps causing problems with fake timers in tests.

### ISSUE THREAD

**Issue by gnarf** [webpack/node-libs-browser#20]
The new version bump for process 0.10.x is causing sinon fake timers + bluebird + webpack to make all bluebird promises "freeze" (because it's now using `setTimeout` instead of the other method it used to (mutation/etc selection process had in 0.8)

Having a hard time figuring how how to undo this problem because webpack itself lists the dep on node-libs-browser to be `~0.4.0` and the bump here is definitely causing problems in all of our test suites that use sinon + bluebird.

**Comment by gnarf** [comment]
Basically doing this: 

```sh
cd node_modules/webpack/node_modules/node-libs-browser ; npm i process@0.8.0
```

Is how I'm fixing it right now, and it works.

**Comment by sokra** [comment]
This should propably be fixed in simon or bluebird... Am I right?

**Comment by gnarf** [comment]
Perhaps, but I think this is an artifact coming from the "browserifying" of it.  The `process.nextTick` implementation in process could hold onto the "real" setTimeout and call it.  Or maybe bluebird could do a better job of detecting fake node "process" and revert back to using mutation observers?  CC @petkaantonov

**Comment by gnarf** [comment]
For reference https://github.com/defunctzombie/node-process/blob/master/browser.js#L28 is the cause of the problem -- the old version in 0.8.0 used a much more clever way that avoided calling the sinon fake timer here: https://github.com/defunctzombie/node-process/blob/v0.8.0/browser.js#L14

**Comment by petkaantonov** [comment]
> maybe bluebird could do a better job of detecting fake node "process" 

I don't think this is the issue given https://github.com/petkaantonov/bluebird/blob/master/src/util.js#L280-L281

**Comment by benjamingr** [comment]
Also worth mentioning you can always tell bluebird explicitly how to schedule via `Promise.setScheduler` - although like Petka said it's not bluebird misdetecting here.

**Comment by gnarf** [comment]
@petkaantonov then why does installing process 0.8.0 again inside the webpack deps fix the problem?

**Comment by sokra** [comment]
@gnarf can you provide a test case so we can play around with it?

**Comment by petkaantonov** [comment]
I didn't look into the real issue here, I was just pointing out that recent versions of bluebird check for authentic process object that cannot be faked without access to native v8 api.

**Comment by gnarf** [comment]
Oh - when did that check get added?  Perhaps I'm still behind on bluebird somewhere.

FWIW this test case fails:

```js
/* global sinon */
require('script!sinon/pkg/sinon');

describe.only('faketime', function() {
  var timers;
  beforeEach(function() {
    timers = sinon.useFakeTimers();
  });
  afterEach(function() {
    timers.restore();
  });
  it('can resolve a promise', function() {
    return require('bluebird').resolve();
  });
});

**Comment by petkaantonov** [comment]
It's in 2.9.6+

**Comment by sokra** [comment]
sinon fake timers do stop `process.nextTick` until you call `timers.tick(ms)`, if I get the documentation correctly...

**Comment by gnarf** [comment]
Except that same test passes with process 0.8.0 instead of 0.10.0 --- it also passes with bluebird 2.9.13+ - so I think I know the answer -- dependency hunt time to figure out what isn't up to date with bluebird

Sorry to take this up as an issue here instead of in bluebird! Thanks for the support @petkaantonov and @sokra

**Comment by KidkArolis** [comment]
I'm running into the same issue with when.js + webpack + sinon.useFakeTimers - all promises seem to break. Does bluebird do something extra to detect it's not actually a node env @gnarf ?

**Comment by gnarf** [comment]
Make sure to use latest bluebird?

**Comment by gnarf** [comment]
Sorry, misread... Look at the scheduler code in bluebird.  The node process
object has a special to string value so you can detect it is node
