### ISSUE TITLE
Modules not found

### ISSUE THREAD

**Issue by be-dcodeit** [webpack/node-libs-browser#26]
When running webpack-dev-server 1.9.0, we get the following errors from node-libs-browser:

ERROR in ./~/node-libs-browser/~/crypto-browserify/pbkdf2.js
Module not found: Error: Cannot resolve module 'pbkdf2-compat/pbkdf2' in H:\XXX\node_modules\node-libs-browser\node_modules\crypto-browserify
 @ ./~/node-libs-browser/~/crypto-browserify/pbkdf2.js 1:19-50

ERROR in ./~/node-libs-browser/~/crypto-browserify/create-hash.js
Module not found: Error: Cannot resolve module 'sha.js' in H:\XXX\node-libs-browser\node_modules\crypto-browserify
 @ ./~/node-libs-browser/~/crypto-browserify/create-hash.js 1:17-34

ERROR in ./~/node-libs-browser/~/crypto-browserify/create-hash.js
Module not found: Error: Cannot resolve module 'ripemd160' in H:\XXX\node_m
odules\node-libs-browser\node_modules\crypto-browserify
 @ ./~/node-libs-browser/~/crypto-browserify/create-hash.js 4:27-47

ERROR in ./~/node-libs-browser/~/buffer/index.js
Module not found: Error: Cannot resolve module 'base64-js' in H:\XXX\node_m
odules\node-libs-browser\node_modules\buffer
 @ ./~/node-libs-browser/~/buffer/index.js 8:13-33

ERROR in ./~/node-libs-browser/~/buffer/index.js
Module not found: Error: Cannot resolve module 'ieee754' in H:\XXX\node_mod
ules\node-libs-browser\node_modules\buffer
 @ ./~/node-libs-browser/~/buffer/index.js 9:14-32

ERROR in ./~/node-libs-browser/~/buffer/index.js
Module not found: Error: Cannot resolve module 'is-array' in H:\XXX\node_mo
dules\node-libs-browser\node_modules\buffer
 @ ./~/node-libs-browser/~/buffer/index.js 10:14-33

**Comment by jhnns** [comment]
Is this still present with node-libs-browser@1.1.0?

**Comment by sojimon** [comment]
I used webpack-dev-server,  "version": "2.1.0-beta.11" and get the following error.

ERROR in (webpack)-dev-server/client?http://localhost:3000
Module not found: Error: Can't resolve 'strip-ansi' in '/var/www/ng2/ng2-admin/node_modules/webpack-dev-server/client'



ERROR in (webpack)-dev-server/client/socket.js
Module not found: Error: Can't resolve 'sockjs-client' in '/var/www/ng2/ng2-admin/node_modules/webpack-dev-server/client'
 @ (webpack)-dev-server/client/socket.js 1:13-37
 
 @ multi polyfills

ERROR in ./~/ng2-bootstrap/components/datepicker/date-formatter.js
Module not found: Error: Can't resolve 'moment' in '/var/www/ng2/ng2-admin/node_modules/ng2-bootstrap/components/datepicker'
 @ ./~/ng2-bootstrap/components/datepicker/date-formatter.js 2:13-30
 @ ./~/ng2-bootstrap/components/datepicker.js
 @ ./~/ng2-bootstrap/ng2-bootstrap.js
 @ ./src/app/app.component.ts
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.browser.ts
 @ multi main

ERROR in ./~/fullcalendar/dist/fullcalendar.js
Module not found: Error: Can't resolve 'moment' in '/var/www/ng2/ng2-admin/node_modules/fullcalendar/dist'
 @ ./~/fullcalendar/dist/fullcalendar.js 9:2-41
 @ ./src/app/theme/components/baFullCalendar/baFullCalendar.loader.ts
 @ ./src/app/theme/components/baFullCalendar/baFullCalendar.component.ts
 @ ./src/app/theme/components/baFullCalendar/index.ts
 @ ./src/app/theme/components/index.ts
 @ ./src/app/theme/nga.module.ts
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.browser.ts
 @ multi main

ERROR in (webpack)/~/node-libs-browser/~/buffer/index.js
Module not found: Error: Can't resolve 'base64-js' in '/var/www/ng2/ng2-admin/node_modules/webpack/node_modules/node-libs-browser/node_modules/buffer'
 @ (webpack)/~/node-libs-browser/~/buffer/index.js 11:13-33
 @ ./~/ng2-smart-table/build/src/ng2-smart-table/lib/helpers.js
 @ ./~/ng2-smart-table/build/src/ng2-smart-table/ng2-smart-table.component.js
 @ ./~/ng2-smart-table/build/ng2-smart-table.js
 @ ./src/app/pages/tables/tables.module.ts
 @ ./src/app/pages/pages.routing.ts
 @ ./src/app/pages/pages.module.ts
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.browser.ts
 @ multi main

ERROR in (webpack)/~/node-libs-browser/~/buffer/index.js
Module not found: Error: Can't resolve 'ieee754' in '/var/www/ng2/ng2-admin/node_modules/webpack/node_modules/node-libs-browser/node_modules/buffer'
 @ (webpack)/~/node-libs-browser/~/buffer/index.js 12:14-32
 @ ./~/ng2-smart-table/build/src/ng2-smart-table/lib/helpers.js
 @ ./~/ng2-smart-table/build/src/ng2-smart-table/ng2-smart-table.component.js
 @ ./~/ng2-smart-table/build/ng2-smart-table.js
 @ ./src/app/pages/tables/tables.module.ts
 @ ./src/app/pages/pages.routing.ts
 @ ./src/app/pages/pages.module.ts
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.browser.ts
 @ multi main

ERROR in (webpack)/~/node-libs-browser/~/buffer/index.js
Module not found: Error: Can't resolve 'isarray' in '/var/www/ng2/ng2-admin/node_modules/webpack/node_modules/node-libs-browser/node_modules/buffer'
 @ (webpack)/~/node-libs-browser/~/buffer/index.js 13:14-32
 @ ./~/ng2-smart-table/build/src/ng2-smart-table/lib/helpers.js
 @ ./~/ng2-smart-table/build/src/ng2-smart-table/ng2-smart-table.component.js
 @ ./~/ng2-smart-table/build/ng2-smart-table.js
 @ ./src/app/pages/tables/tables.module.ts
 @ ./src/app/pages/pages.routing.ts
 @ ./src/app/pages/pages.module.ts
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.browser.ts
 @ multi main

**Comment by SpaceK33z** [comment]
@sojimon this generally happens when you overwrite `resolve.modules`, but don't include `'node_modules'` in the array.

**Comment by sojimon** [comment]
@SpaceK33z  Now it is ok.Thanks ..

**Comment by SpaceK33z** [comment]
I'm fairly sure @be-dcodeit's issue is because of the same config issue from above. Let's close this, we can always re-open if it turns out to be an issue of node-libs-browser, but I'm pretty sure it won't.
