### ISSUE TITLE
alternative mapping for react-native

### ISSUE THREAD

**Issue by mvayngrib** [webpack/node-libs-browser#27]
I'm trying to use this with react-native, but with additional shims for [fs](https://www.npmjs.org/package/react-native-level-fs), [dgram](https://www.npmjs.org/package/react-native-udp), [dns.js](https://www.npmjs.org/package/dns.js) and [net](https://www.npmjs.org/package/utp). Right now I'm using a [fork](https://github.com/webpack/node-libs-browser/compare/master...mvayngrib:master) of this repo (and a [fork](https://github.com/webpack/webpack/compare/master...mvayngrib:master) of webpack because peerDependencies doesn't like git urls), but I thought maybe you had a better idea.

**Comment by mvayngrib** [comment]
maybe that can be an option in webpack config - the ability to provide an alternate node-libs-browser?

**Comment by sokra** [comment]
You can provide alternatives via `resolve.alias` option.
