### ISSUE TITLE
Merge xxx-browserify or not?

### ISSUE THREAD

**Issue by sokra** [webpack/node-libs-browser#3]
Should the xxx-browserify modules and authors merged into this package?

Pro:
- less fragmentation
- more maintainers for all node buildin libs
- easier sharing of small common fragments, i.e. shims
- easier to maintain

Contra:
- less modular
- "holy fuck. why are there 20 files and 1000s of lines of code in one repo"

Problems merging:
- xxx-browserify modules could not longer be used alone
  - they can transform into wrappers for this package

Problems splitting:
- duplicated effort to have each module tested in testling
- no aggregated test results
  - repo for aggregating results
  - badge wouldn't update

**Comment by QuantumInformation** [comment]
Can you pipe webpack to testling instead of browserify?
