### ISSUE TITLE
Needs better documentation

### ISSUE THREAD

**Issue by zenflow** [webpack/node-libs-browser#30]
@webpack 

This repo would ideally give a bit more details in the readme, for easy reference.

* which modules are implemented (for example, `'process'`) and which are not (for example, `'fs'`)
* how the implemented modules differ from their node counterparts
 
I would gladly volunteer to take this task if it pleases you. 

I'll note that it's of particular importance to me that the `browser` member of `process` (i.e. `process.browser`) gets documented. It would be a brief mention, and I would by no means go into details or examples of how to use it, but I will breifly argue it's significance to you here...

You can reference `process.browser` in isomorphic code that
* adjusts it's behavior depending on which environment it's in
* is fully portable within the nodejs/iojs/browserify/webpack ecosystem, and
* is concise and Don't Repeat Yourself (DRY)

That said, I intend on doing a thorough documentation of each module, not just `process`, should you welcome my offer to help.

So, I guess my question is: Would you like to see a PR with enhanced documentation as described?

**Comment by zenflow** [comment]
@sokra I'll take no response as a thumbs-up to do this and submit a PR :)

**Comment by sokra** [comment]
:+1:

This package only references the individual npm packages for the browser variants. For detailed documentation you should be able the link to the readmes.

**Comment by zenflow** [comment]
@sokra: ping
