### ISSUE TITLE
crypto-browserify version needs update to work with some (?) webpack builds

### ISSUE THREAD

**Issue by designreact** [webpack/node-libs-browser#34]
Given "crypto-browserify": "~3.2.6", 

Bundled (React) Webpack output errors with: 'Uncaught ReferenceError: _crypto is not defined'

This is I believe fixed in crypto-browserify 3.9.14

https://github.com/crypto-browserify/crypto-browserify/commit/30d96df5f6cdbe8ecdb4e7ef584a218ba3e302e2

Any chance of an update?

**Comment by designreact** [comment]
... I created a pull request https://github.com/webpack/node-libs-browser/pull/35

**Comment by yurynix** [comment]
Also more functions are implemented there, such as `createVerify`, which are needed for libs such as `jsonwebtoken`.
