### ISSUE TITLE
Use stream-http

### ISSUE THREAD

**Issue by feross** [webpack/node-libs-browser#38]
Browserify has stopped using `http-browserify` and moved to [`stream-http`](https://www.npmjs.com/package/stream-http) which actually supports true response streaming and has lots of bug fixes.

webpack should probably switch over too.

This would fix [this bug](https://github.com/feross/webtorrent/issues/768#issuecomment-214949683) when WebTorrent is built with webpack.

cc @jhiesey

**Comment by terinjokes** [comment]
:+1: I `npm install`ed webpack for the first time today and was shocked when I saw `http-browserify` still being used by `node-libs-browser`.

**Comment by RomanGotsiy** [comment]
@terinjokes I believe `https-browserify` should be replaced with `streem-http` too.
Check out this issue https://github.com/substack/https-browserify/issues/6.

**Comment by feross** [comment]
Can you publish this to npm so that webpack users can get the update?

**Comment by feross** [comment]
Ping @sokra – this bug still isn't fixed in webpack because `node-libs-browser` was not published to npm. Can you do that real quick?

**Comment by RomanGotsiy** [comment]
@feross as a temporal workaround I'm using [`resolve.alias`](https://webpack.github.io/docs/configuration.html#resolve-alias):

```js
resolve: {
  alias: {
    http: 'stream-http',
    https: 'stream-http'
  }
}
```
