### ISSUE TITLE
Any chance of updating latest pre-1.0 version to use newer version of buffer?

### ISSUE THREAD

**Issue by bergr01** [webpack/node-libs-browser#39]
Hi
I'm currently using latest stable version of webpack (1.13.0) that relies on "node-libs-browser": ">= 0.4.0 <=0.6.0" which in turn uses "buffer": "^3.0.3". Any chance of bumping that up to utilize buffer 4.3.0 that's used by node-libs-browser v1.0? I'm running into an issue that was resolved in buffer since 3.0.3 and would prefer not to edit the buffer source under node_modules manually on x of the build machines.

**Comment by feross** [comment]
I posted a similar issue about the need to update `stream-http`. https://github.com/webpack/node-libs-browser/issues/38

I don't even use webpack, so I could care less. But I help maintain buffer and webtorrent and both have seen opened issues by webpack users complaining about already fixed bugs because webpack is using old versions of buffer and stream-http.

**Comment by feross** [comment]
Oh, misunderstood this issue. The latest buffer is already in `package.json`. You're asking them to bump an old version. Good luck with that.

**Comment by orlandodemauro** [comment]
@bergr01 issue fixed in https://github.com/webpack/node-libs-browser/pull/42. new node-libs-browser package published (v0.6.0) with buffer v^4.9.0 dependency. it will be automatically picked by webpack 1.13.0. This issue can be closed

**Comment by Offirmo** [comment]
@orlandodemauro I have an install issue since your update https://github.com/webpack/node-libs-browser/issues/43

**Comment by jhnns** [comment]
We will bump node-libs-browser to `^1.1.0` in webpack-1, see https://github.com/webpack/webpack/issues/3355

**Comment by jhnns** [comment]
There was a hidden breaking change with `crypto-browserify` so that we couldn't upgrade it to the most recent version. However, [this PR](https://github.com/webpack/webpack/pull/3368) introduces the most recent versions without breaking change to webpack-1.
