### ISSUE TITLE
Update to crypto-browserify 3.11.0 in your 0.5.3 version

### ISSUE THREAD

**Issue by edi9999** [webpack/node-libs-browser#40]
The version 0.5.3 of node-libs-browser currently depends on : 

`"crypto-browserify": "^3.2.6",`

Which it self depends on `ripemd160@0.2.0` which was unlicensed.
This poses a problem for any webpack users since webpack uses version 0.5.3 of node-libs-browser.

Can you please release a new 0.5.4 version with crypto-browseriify 3.11.0 ?

This way, all sub licenses of webpack are conform with the license of webpack it self.

**Comment by sl-church** [comment]
I second this request.  I am trying to incorporate JWT signing in an app and 3.2.6 does not support signing while the latest version does.  Currently I just install the latest version with npm and delete the version under node-libs-browser.  This works but I have to do the deletion every time I install a package. 

Thanks.

**Comment by terinjokes** [comment]
@sokra There's a handful of issues asking for a `0.5.4` release. Alternatively, is there a reason to not upgrade the dependency of Webpack v1 to `node-libs-browser@^1.0.0`?

**Comment by jhnns** [comment]
We will bump node-libs-browser to `^1.1.0` in webpack-1, see https://github.com/webpack/webpack/issues/3355

**Comment by jhnns** [comment]
There was a hidden breaking change with `crypto-browserify` so that we couldn't upgrade it to the most recent version. However, [this PR](https://github.com/webpack/webpack/pull/3368) introduces the most recent versions without breaking change to webpack-1.
