### ISSUE TITLE
npm ERR! No compatible version found: node-libs-browser@^0.6.0

### ISSUE THREAD

**Issue by Offirmo** [webpack/node-libs-browser#43]
Doing a fresh npm install this morning :

```
npm ERR! No compatible version found: node-libs-browser@^0.6.0
npm ERR! Valid install targets:
npm ERR! 1.0.0, 0.5.3, 0.5.2, 0.5.1, 0.5.0, 0.4.3, 0.4.2, 0.4.1, 0.4.0, 0.3.1, 0.3.0, 0.2.1, 0.2.0, 0.1.2, 0.1.1, 0.1.0
```

This is breaking npm install

Did the new 0.6.0 get pushed to npm ? Who is referencing it ? (most likely babel)

**Comment by Offirmo** [comment]
most likely related to https://github.com/webpack/node-libs-browser/issues/39#issuecomment-240661614

**Comment by jaylone** [comment]
yeah. I found that node-libs-browser@0.6.0 was not available on npm platform.

**Comment by sokra** [comment]
It's published. travis has no problem installing it: https://travis-ci.org/webpack/webpack/jobs/153204447#L620

**Comment by sokra** [comment]
try to flush the npm cache

**Comment by Offirmo** [comment]
I checked on npm API when reporting, it was not listed at the time.

However, it works now: npm must have had a DB replication glitch.

All clear ! And thanks for all the good work !
