### ISSUE TITLE
why has this become deprecated?

### ISSUE THREAD

**Issue by millsp** [webpack/node-libs-browser#94]
I see this is still in the docs for webpack. How should we polyfill nodejs apis in the future? @sokra

**Comment by sokra** [comment]
You can still use the individual polyfills, only the wrapper package has been deprecated as webpack 5 will no longer use it by default.

**Comment by millsp** [comment]
Thanks! This package was really convenient, though.

**Comment by pcowgill** [comment]
Should we add the reason for deprecation in the `README` too?

**Comment by pcowgill** [comment]
Does webpack 5 use the individual polyfills, and if so, is there an up-to-date list of those?

**Comment by malinin01** [comment]
@sokra will it still be possible to assign polyfills to native node.js modules in webpack5 or developers will need to create and maintain such a wrapper package themselves?

**Comment by jimmywarting** [comment]
> Should we add the reason for deprecation in the README too?

☝️  would also like to know why, but figure it had to do with webpack 5?

**Comment by sokra** [comment]
You don't need to create your own wrapper package. In webpack 5 we show an error message with steps what you need to do when you or some node_modules use some node.js built-in module without browser fallback.

**Comment by niksy** [comment]
If anyone is looking up-to-date version of polyfills, I’ve created [`node-stdlib-browser`](https://github.com/niksy/node-stdlib-browser) as alternative which is updated and has many other features such as official support for other bundlers.
